---

- hosts: localhost
  gather_facts: False

  vars:
    region: us-east-2
    instance_type: t2.micro
    ami: mi-0b500ef59d8335eee
    keypair: Redhat practise

  tasks:
    - name: Create new EC2 Instance
      ec2:
        key name: "{( keypair )}"
        aws_access_key: "{{ AKIAJJ5HBTGSQ6YCU4FA }}"
        aws_secret_key: "{{ 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 }}"
        group: launch-wizard-12 #security group name
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        count: 1
        count_tag:
          Name: "Demo"
        instance_tags:
          Name: "Demo"
        vpc_subnet_id: "subnet-afe13fe3"
        assign_public_ip: yes
      register: ec2

    - name: print ec2 module output
      debug: var=ec2

    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

    - set_fact: ip_list= "[]"

    - name: Construct IP List
      set_fact: ip_list= "{{ ip_list }} + ['{{ item.private_ip }}']"
      with_items: "{{ ec2.instances }}"

    - name: Print IP List
      debug: msg="{{ ip_list }}"
